package com.web;
/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.dao.AddresstableDAO;

/** 
 * MyEclipse Struts
 * Creation date: 12-02-2017
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class ListContactAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		
		AddresstableDAO dao = new AddresstableDAO();
		List list = dao.findAll();
		request.getSession().setAttribute("list", list);
		
		return mapping.findForward("success");
	}
}